// src/lib/constants/cities.ts
export interface City {
  name_en: string;
  name_ps: string;
  name_fa: string;
  country: string;
  latitude: number;
  longitude: number;
  featured: boolean;
}

export const POPULAR_CITIES: City[] = [
  // Afghanistan - All Cities
  {
    name_en: 'Kabul',
    name_ps: 'کابل',
    name_fa: 'کابل',
    country: 'Afghanistan',
    latitude: 34.5199,
    longitude: 69.1976,
    featured: true,
  },
  {
    name_en: 'Kandahar',
    name_ps: 'کندھار',
    name_fa: 'قندهار',
    country: 'Afghanistan',
    latitude: 31.6068,
    longitude: 65.7096,
    featured: true,
  },
  {
    name_en: 'Herat',
    name_ps: 'ہرات',
    name_fa: 'هرات',
    country: 'Afghanistan',
    latitude: 34.3425,
    longitude: 62.1944,
    featured: true,
  },
  {
    name_en: 'Mazar-e-Sharif',
    name_ps: 'مزار شریف',
    name_fa: 'مزار شریف',
    country: 'Afghanistan',
    latitude: 36.7169,
    longitude: 67.1285,
    featured: true,
  },
  {
    name_en: 'Jalalabad',
    name_ps: 'جلال آباد',
    name_fa: 'جلال‌آباد',
    country: 'Afghanistan',
    latitude: 34.4256,
    longitude: 70.4780,
    featured: false,
  },
  {
    name_en: 'Kunduz',
    name_ps: 'کندوز',
    name_fa: 'کندوز',
    country: 'Afghanistan',
    latitude: 36.7363,
    longitude: 68.8667,
    featured: false,
  },
  {
    name_en: 'Ghazni',
    name_ps: 'غزنی',
    name_fa: 'غزنی',
    country: 'Afghanistan',
    latitude: 33.5505,
    longitude: 68.4267,
    featured: false,
  },
  {
    name_en: 'Lashkargah',
    name_ps: 'لشکر گاه',
    name_fa: 'لشکرگاه',
    country: 'Afghanistan',
    latitude: 31.9853,
    longitude: 64.3597,
    featured: false,
  },
  {
    name_en: 'Khost',
    name_ps: 'خوست',
    name_fa: 'خوست',
    country: 'Afghanistan',
    latitude: 33.3392,
    longitude: 69.9189,
    featured: false,
  },
  {
    name_en: 'Gardez',
    name_ps: 'ګردیز',
    name_fa: 'گردیز',
    country: 'Afghanistan',
    latitude: 33.5930,
    longitude: 69.2153,
    featured: false,
  },
  {
    name_en: 'Taloqan',
    name_ps: 'تلوقان',
    name_fa: 'تالقان',
    country: 'Afghanistan',
    latitude: 36.7383,
    longitude: 69.5361,
    featured: false,
  },
  {
    name_en: 'Puli Khumri',
    name_ps: 'پل خمری',
    name_fa: 'پل خمری',
    country: 'Afghanistan',
    latitude: 35.9378,
    longitude: 68.7056,
    featured: false,
  },
  {
    name_en: 'Sheberghan',
    name_ps: 'شبرغان',
    name_fa: 'شبرغان',
    country: 'Afghanistan',
    latitude: 36.6689,
    longitude: 65.7492,
    featured: false,
  },
  {
    name_en: 'Charikar',
    name_ps: 'چاریکار',
    name_fa: 'چاریکار',
    country: 'Afghanistan',
    latitude: 35.3200,
    longitude: 69.1683,
    featured: false,
  },
  {
    name_en: 'Sar-e Pol',
    name_ps: 'سرپل',
    name_fa: 'سرپل',
    country: 'Afghanistan',
    latitude: 36.2133,
    longitude: 67.0667,
    featured: false,
  },
  {
    name_en: 'Aybak',
    name_ps: 'ایباک',
    name_fa: 'ایباک',
    country: 'Afghanistan',
    latitude: 35.9258,
    longitude: 67.2667,
    featured: false,
  },
  {
    name_en: 'Mehtarlam',
    name_ps: 'مختارلام',
    name_fa: 'مختارلام',
    country: 'Afghanistan',
    latitude: 34.6433,
    longitude: 70.2172,
    featured: false,
  },
  {
    name_en: 'Faizabad',
    name_ps: 'فیض آباد',
    name_fa: 'فیض‌آباد',
    country: 'Afghanistan',
    latitude: 37.1186,
    longitude: 71.3144,
    featured: false,
  },
  {
    name_en: 'Zaranj',
    name_ps: 'زرنج',
    name_fa: 'زرنج',
    country: 'Afghanistan',
    latitude: 30.9667,
    longitude: 61.8667,
    featured: false,
  },
  {
    name_en: 'Farah',
    name_ps: 'فراه',
    name_fa: 'فراه',
    country: 'Afghanistan',
    latitude: 32.3667,
    longitude: 62.1167,
    featured: false,
  },
  {
    name_en: 'Bamyan',
    name_ps: 'بامیان',
    name_fa: 'باميان',
    country: 'Afghanistan',
    latitude: 34.8089,
    longitude: 67.8297,
    featured: false,
  },
  {
    name_en: 'Nili',
    name_ps: 'نیلی',
    name_fa: 'نیلی',
    country: 'Afghanistan',
    latitude: 34.6667,
    longitude: 67.9167,
    featured: false,
  },
  {
    name_en: 'Chaghcharan',
    name_ps: 'غور',
    name_fa: 'غور',
    country: 'Afghanistan',
    latitude: 34.5167,
    longitude: 65.2500,
    featured: false,
  },
  {
    name_en: 'Mahmud Raqi',
    name_ps: 'محمود راقی',
    name_fa: 'محمود راقی',
    country: 'Afghanistan',
    latitude: 35.3025,
    longitude: 69.5089,
    featured: false,
  },
  {
    name_en: 'Asadabad',
    name_ps: 'اسد آباد',
    name_fa: 'اسد‌آباد',
    country: 'Afghanistan',
    latitude: 34.8667,
    longitude: 71.1833,
    featured: false,
  },
  {
    name_en: 'Panjshir',
    name_ps: 'پنجشیر',
    name_fa: 'پنجشیر',
    country: 'Afghanistan',
    latitude: 35.2500,
    longitude: 69.5333,
    featured: false,
  },
  {
    name_en: 'Parwan',
    name_ps: 'پروان',
    name_fa: 'پروان',
    country: 'Afghanistan',
    latitude: 35.2200,
    longitude: 69.0500,
    featured: false,
  },
  {
    name_en: 'Maidan Shar',
    name_ps: 'میدان شار',
    name_fa: 'میدان شار',
    country: 'Afghanistan',
    latitude: 34.5167,
    longitude: 68.7000,
    featured: false,
  },
  {
    name_en: 'Tarin Kowt',
    name_ps: 'تارین کوٹ',
    name_fa: 'تاریں کوت',
    country: 'Afghanistan',
    latitude: 32.7667,
    longitude: 65.8667,
    featured: false,
  },
  {
    name_en: 'Qalat',
    name_ps: 'قلات',
    name_fa: 'قلات',
    country: 'Afghanistan',
    latitude: 32.9667,
    longitude: 66.9167,
    featured: false,
  },
  {
    name_en: 'Pol-e Alam',
    name_ps: 'پل علم',
    name_fa: 'پل علم',
    country: 'Afghanistan',
    latitude: 34.3500,
    longitude: 69.4667,
    featured: false,
  },
  {
    name_en: 'Parun',
    name_ps: 'پرون',
    name_fa: 'پرون',
    country: 'Afghanistan',
    latitude: 36.2167,
    longitude: 71.5333,
    featured: false,
  },
  {
    name_en: 'Bazarak',
    name_ps: 'بازارک',
    name_fa: 'بازارک',
    country: 'Afghanistan',
    latitude: 35.3222,
    longitude: 69.4778,
    featured: false,
  },
  {
    name_en: 'Samangan',
    name_ps: 'سمنگان',
    name_fa: 'سمنگان',
    country: 'Afghanistan',
    latitude: 36.1833,
    longitude: 68.0333,
    featured: false,
  },
  // Additional Regional Cities
  {
    name_en: 'Istanbul',
    name_ps: 'استنبول',
    name_fa: 'استانبول',
    country: 'Turkey',
    latitude: 41.0082,
    longitude: 28.9784,
    featured: false,
  },
  {
    name_en: 'Peshawar',
    name_ps: 'پیشاور',
    name_fa: 'پشاور',
    country: 'Pakistan',
    latitude: 34.0151,
    longitude: 71.5249,
    featured: false,
  },
  {
    name_en: 'Lahore',
    name_ps: 'لاہور',
    name_fa: 'لاهور',
    country: 'Pakistan',
    latitude: 31.5204,
    longitude: 74.3587,
    featured: false,
  },
  {
    name_en: 'Karachi',
    name_ps: 'کراچی',
    name_fa: 'کراچی',
    country: 'Pakistan',
    latitude: 24.8607,
    longitude: 67.0011,
    featured: false,
  },
];

export const getCityName = (cityName: string, locale: 'en' | 'ps' | 'fa'): string => {
  const city = POPULAR_CITIES.find((c) => c.name_en.toLowerCase() === cityName.toLowerCase());
  if (!city) return cityName;

  switch (locale) {
    case 'en':
      return city.name_en;
    case 'ps':
      return city.name_ps;
    case 'fa':
      return city.name_fa;
    default:
      return city.name_en;
  }
};
